on:
  push:
    branches:
    - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run tests with cucumber
        run: npx cucumber-js --tags @Regression
      - name: Create test summary
        uses: ./bin
        with:
          paths: test/results/*.xml
          output: test/results/results.html
      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test/results/results.html
        if: always()
          