on:
  push:
    branches:
    - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Install playwright browsers
        run: npx playwright install
      - name: Run tests with cucumber
        run: npx cucumber-js --tags @Regression --exit
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "test/results/cucumber-report.xml"
        if: always()
